function animate (svg, data, coords, histogram, duration, index) {

  // primary animation loop for molecules
  
  var pill = svg.selectAll('.pill' + index).remove()

  var pill = svg.selectAll('.pill' + index)
      .data(data.data)
    .enter().append('rect')
      .attr('class', 'pill' + index)
      .attr('width', 0)
      .attr('height', 0)
      .attr('transform', 'translate(10,4)')
      .attr('rx', 7)
      .attr('ry', 10)
      .attr('x', function (d) {return coords.cell.x(d[0])})
      .attr('y', function (d) {return coords.cell.y(d[1])})
      .style('fill', function (d) {
        if (d[2] == 1) return '#F768A1'
        return '#C4C4C4'
      })
      .style('opacity', 0.75)
    .transition()
      .duration(duration * 0.2)
      .attr('width', 40)
      .attr('height', 15)
      .attr('transform', 'translate(-10,-4)')
    .transition()
      .duration(duration * 0.2)
      .attr('x', function (d) {return coords.sample.x(d[3])})
      .attr('y', function (d) {return coords.sample.y(d[4])})
    .transition()
      .duration(duration * 0.1)
      .attr('width', function (d) {return (d[5] ? 40 : 0)})
      .attr('height', function (d) {return (d[5] ? 15 : 0)})
      .attr('transform', function (d) {return (d[5] ? 'translate(-10,-4)' : 'translate(10,4)')})
    .transition()
      .duration(duration * 0.1)
      .attr('transform', function (d) {return (d[6] ? 'translate(-5,-9)' : 'translate(-10,-4)')})
    .transition()
      .duration(duration * 0.15)
      .attr('x', function (d) {return coords.sample.x(d[7])})
      .attr('y', function (d) {return coords.sample.y(d[8])})
      .attr('transform', 'translate(-10,-4)')
      .style('stroke', 'none')
    .transition()
      .duration(duration * 0.1)
      .style('opacity', function (d) {return (d[2] == 0) ? 0 : 1})
    .transition()
      .duration(duration * 0.15)
      .attr('x', function (d) {return histogram.x(d[9])})
      .attr('y', function (d) {return histogram.y(0.01)})
      .attr('width', 20)
      .attr('height', 20)
      .attr('rx', 10)
      .attr('ry', 10)
      //.on('end', console.log('all done'))
}

module.exports = animate